[06-Sep-25 08:11:33 - WARNING] - bot - Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.GetChannels")
[06-Sep-25 08:11:33 - WARNING] - bot - Bot can't Export Invite link from Force Sub Channel!
[06-Sep-25 08:11:33 - WARNING] - bot - Please Double check the FORCE_SUB_CHANNEL value and Make sure Bot is Admin in channel with Invite Users via Link Permission, Current Force Sub Channel Value: -1002108419450
[06-Sep-25 08:11:33 - INFO] - bot - 
Bot Stopped. Join https://t.me/ultroid_official for support
[06-Sep-25 08:13:17 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:13:17 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:13:18 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:08:13:18 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Arv2%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 08:19:22 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:19:31 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:19:31 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:24:05 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:24:06 - INFO] - bot - Bot stopped.
[06-Sep-25 08:24:20 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:24:20 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:28:31 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:28:32 - INFO] - bot - Bot stopped.
[06-Sep-25 08:28:37 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:28:37 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:28:38 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:08:28:38 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar18f%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 08:30:12 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:30:23 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:30:23 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:30:24 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:08:30:24 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar19s%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 08:32:12 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:32:19 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:32:19 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:33:21 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:33:23 - INFO] - bot - Bot stopped.
[06-Sep-25 08:33:27 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:33:27 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:33:28 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:08:33:28 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar1e5%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 08:38:55 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:38:56 - INFO] - bot - Bot stopped.
[06-Sep-25 08:39:04 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:39:04 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:41:35 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:41:46 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:41:46 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:42:28 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:44:28 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:44:28 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:44:29 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:08:44:29 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar1o6%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 08:48:20 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:48:21 - INFO] - bot - Bot stopped.
[06-Sep-25 08:48:32 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:48:32 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:48:33 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:08:48:33 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar1tm%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 08:50:08 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:50:11 - INFO] - bot - Bot stopped.
[06-Sep-25 08:51:06 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:51:06 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:53:47 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:53:49 - INFO] - bot - Bot stopped.
[06-Sep-25 08:53:55 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:53:55 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 08:53:57 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:08:53:57 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar23i%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 08:53:58 - ERROR] - pyrogram.dispatcher - is_subscribed() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/plugins/start.py", line 117, in start_handler
    if not await subscribed(filters, client, message):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: is_subscribed() takes 3 positional arguments but 4 were given
[06-Sep-25 08:54:47 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 08:54:49 - INFO] - bot - Bot stopped.
[06-Sep-25 08:54:54 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 08:54:54 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 09:03:54 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 09:04:10 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 09:04:10 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 09:04:11 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:09:04:11 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar2nm%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 09:09:08 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 09:09:09 - INFO] - bot - Bot stopped.
[06-Sep-25 09:11:02 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 09:11:02 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 09:11:03 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:09:11:03 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar2qo%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 09:14:08 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 09:14:10 - INFO] - bot - Bot stopped.
[06-Sep-25 09:14:34 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 09:14:34 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 09:14:35 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:09:14:35 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar2s8%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 09:18:44 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 09:18:58 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 09:18:58 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 09:18:59 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:09:18:59 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar2to%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 09:26:25 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 09:26:27 - INFO] - bot - Bot stopped.
[06-Sep-25 09:26:37 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 09:26:37 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 09:26:38 - INFO] - aiohttp.access - 172.31.97.98 [06/Sep/2025:09:26:38 +0000] "GET / HTTP/1.1" 200 178 "https://2afc7d04-7d04-4379-9cd9-9c80382bddcd-00-3sw0k737hgeel.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar31a%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 09:37:09 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 09:37:11 - INFO] - bot - Bot stopped.
[06-Sep-25 09:37:19 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 09:37:19 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 09:49:38 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 09:49:38 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 09:49:39 - INFO] - aiohttp.access - 172.31.77.194 [06/Sep/2025:09:49:39 +0000] "GET / HTTP/1.1" 200 178 "https://1005ec4c-1b6b-4486-9fbc-72b6e11a82bb-00-3757v57maq7g7.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Arck%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 09:53:02 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 09:53:47 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 09:53:47 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 09:57:36 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 09:57:36 - INFO] - bot - Bot stopped.
[06-Sep-25 09:57:41 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 09:57:41 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 09:59:25 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 09:59:33 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 09:59:33 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 10:02:08 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 10:02:15 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 10:02:15 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 10:04:54 - ERROR] - pyrogram.dispatcher - cannot access local variable 'asyncio' where it is not associated with a value
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/plugins/start.py", line 34, in start_handler
    await asyncio.sleep(2)
          ^^^^^^^
UnboundLocalError: cannot access local variable 'asyncio' where it is not associated with a value
[06-Sep-25 10:04:57 - ERROR] - pyrogram.dispatcher - cannot access local variable 'asyncio' where it is not associated with a value
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/plugins/start.py", line 34, in start_handler
    await asyncio.sleep(2)
          ^^^^^^^
UnboundLocalError: cannot access local variable 'asyncio' where it is not associated with a value
[06-Sep-25 10:04:59 - ERROR] - pyrogram.dispatcher - cannot access local variable 'asyncio' where it is not associated with a value
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/plugins/start.py", line 34, in start_handler
    await asyncio.sleep(2)
          ^^^^^^^
UnboundLocalError: cannot access local variable 'asyncio' where it is not associated with a value
[06-Sep-25 10:05:00 - ERROR] - pyrogram.dispatcher - cannot access local variable 'asyncio' where it is not associated with a value
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/plugins/start.py", line 34, in start_handler
    await asyncio.sleep(2)
          ^^^^^^^
UnboundLocalError: cannot access local variable 'asyncio' where it is not associated with a value
[06-Sep-25 10:05:02 - ERROR] - pyrogram.dispatcher - cannot access local variable 'asyncio' where it is not associated with a value
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/plugins/start.py", line 34, in start_handler
    await asyncio.sleep(2)
          ^^^^^^^
UnboundLocalError: cannot access local variable 'asyncio' where it is not associated with a value
[06-Sep-25 10:14:13 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 10:14:13 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 10:14:14 - INFO] - aiohttp.access - 172.31.77.194 [06/Sep/2025:10:14:14 +0000] "GET / HTTP/1.1" 200 178 "https://1005ec4c-1b6b-4486-9fbc-72b6e11a82bb-00-3757v57maq7g7.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar116%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 10:17:07 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 10:17:07 - INFO] - bot - Bot stopped.
[06-Sep-25 10:17:13 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 10:17:13 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 10:17:14 - INFO] - aiohttp.access - 172.31.77.194 [06/Sep/2025:10:17:14 +0000] "GET / HTTP/1.1" 200 178 "https://1005ec4c-1b6b-4486-9fbc-72b6e11a82bb-00-3757v57maq7g7.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar15k%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 10:19:23 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 10:19:31 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 10:19:31 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 10:19:32 - INFO] - aiohttp.access - 172.31.77.194 [06/Sep/2025:10:19:32 +0000] "GET / HTTP/1.1" 200 178 "https://1005ec4c-1b6b-4486-9fbc-72b6e11a82bb-00-3757v57maq7g7.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar184%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 10:19:51 - ERROR] - pyrogram.dispatcher - cannot access local variable 'asyncio' where it is not associated with a value
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/plugins/start.py", line 39, in start_handler
    await asyncio.sleep(2)
          ^^^^^^^
UnboundLocalError: cannot access local variable 'asyncio' where it is not associated with a value
[06-Sep-25 10:21:50 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 10:22:04 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 10:22:04 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 10:22:12 - ERROR] - pyrogram.dispatcher - cannot access local variable 'asyncio' where it is not associated with a value
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/plugins/start.py", line 39, in start_handler
    await asyncio.sleep(2)
          ^^^^^^^
UnboundLocalError: cannot access local variable 'asyncio' where it is not associated with a value
[06-Sep-25 10:23:02 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 10:23:03 - INFO] - bot - Bot stopped.
[06-Sep-25 10:23:08 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 10:23:08 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 10:23:09 - INFO] - aiohttp.access - 172.31.77.194 [06/Sep/2025:10:23:09 +0000] "GET / HTTP/1.1" 200 178 "https://1005ec4c-1b6b-4486-9fbc-72b6e11a82bb-00-3757v57maq7g7.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar1di%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 10:32:17 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 10:34:17 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 10:34:17 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 10:34:18 - INFO] - aiohttp.access - 172.31.77.194 [06/Sep/2025:10:34:18 +0000] "GET / HTTP/1.1" 200 178 "https://1005ec4c-1b6b-4486-9fbc-72b6e11a82bb-00-3757v57maq7g7.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar1i6%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 10:37:47 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 10:37:50 - INFO] - bot - Bot stopped.
[06-Sep-25 10:40:30 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 10:40:30 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 10:40:31 - INFO] - aiohttp.access - 172.31.77.194 [06/Sep/2025:10:40:31 +0000] "GET / HTTP/1.1" 200 0 "https://1005ec4c-1b6b-4486-9fbc-72b6e11a82bb-00-3757v57maq7g7.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar1nh%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 10:42:59 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 10:43:52 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 10:43:52 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 10:43:53 - INFO] - aiohttp.access - 172.31.77.194 [06/Sep/2025:10:43:53 +0000] "GET / HTTP/1.1" 200 178 "https://1005ec4c-1b6b-4486-9fbc-72b6e11a82bb-00-3757v57maq7g7.pike.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar1rl%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 10:44:31 - ERROR] - pyrogram.dispatcher - Connection timeout to host https://arolinks.com/api?api=dc64f71dee43e715379e1da5d3bc9dbeb96b71a7&url=https://telegram.dog/newxxxiobot?start%3Dverify_kbIn7ugNRj&alias=&format=json
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/connector.py", line 1268, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohappyeyeballs/impl.py", line 73, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohappyeyeballs/impl.py", line 208, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/asyncio/selector_events.py", line 638, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/client.py", line 725, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/connector.py", line 642, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/connector.py", line 1581, in _create_direct_connection
    raise last_exc
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/connector.py", line 1550, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/connector.py", line 1265, in _wrap_create_connection
    async with ceil_timeout(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/shortzy/adlinkfly.py", line 49, in convert
    data = await self.__fetch(session, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/shortzy/adlinkfly.py", line 17, in __fetch
    async with session.get(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/client.py", line 1488, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/client.py", line 770, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/client.py", line 729, in _connect_and_send_request
    raise ConnectionTimeoutError(
aiohttp.client_exceptions.ConnectionTimeoutError: Connection timeout to host https://arolinks.com/api?api=dc64f71dee43e715379e1da5d3bc9dbeb96b71a7&url=https://telegram.dog/newxxxiobot?start%3Dverify_kbIn7ugNRj&alias=&format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/plugins/start.py", line 87, in start_handler
    link = await get_shortlink(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/helper_func.py", line 137, in get_shortlink
    link = await shortzy.convert(link)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/shortzy/main.py", line 56, in convert
    return await self.shortener.convert(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/shortzy/adlinkfly.py", line 60, in convert
    raise Exception(e)
Exception: Connection timeout to host https://arolinks.com/api?api=dc64f71dee43e715379e1da5d3bc9dbeb96b71a7&url=https://telegram.dog/newxxxiobot?start%3Dverify_kbIn7ugNRj&alias=&format=json
[06-Sep-25 10:44:59 - ERROR] - pyrogram.dispatcher - Connection timeout to host https://arolinks.com/api?api=dc64f71dee43e715379e1da5d3bc9dbeb96b71a7&url=https://telegram.dog/newxxxiobot?start%3Dverify_Wt9l6CSwIq&alias=&format=json
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/connector.py", line 1268, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohappyeyeballs/impl.py", line 73, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohappyeyeballs/impl.py", line 208, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/asyncio/selector_events.py", line 638, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/client.py", line 725, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/connector.py", line 642, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/connector.py", line 1581, in _create_direct_connection
    raise last_exc
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/connector.py", line 1550, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/connector.py", line 1265, in _wrap_create_connection
    async with ceil_timeout(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/shortzy/adlinkfly.py", line 49, in convert
    data = await self.__fetch(session, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/shortzy/adlinkfly.py", line 17, in __fetch
    async with session.get(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/client.py", line 1488, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/client.py", line 770, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/aiohttp/client.py", line 729, in _connect_and_send_request
    raise ConnectionTimeoutError(
aiohttp.client_exceptions.ConnectionTimeoutError: Connection timeout to host https://arolinks.com/api?api=dc64f71dee43e715379e1da5d3bc9dbeb96b71a7&url=https://telegram.dog/newxxxiobot?start%3Dverify_Wt9l6CSwIq&alias=&format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7d088dip86hlzri9sk0h78b63yfmx0a0-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/plugins/start.py", line 87, in start_handler
    link = await get_shortlink(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/helper_func.py", line 137, in get_shortlink
    link = await shortzy.convert(link)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/shortzy/main.py", line 56, in convert
    return await self.shortener.convert(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/shortzy/adlinkfly.py", line 60, in convert
    raise Exception(e)
Exception: Connection timeout to host https://arolinks.com/api?api=dc64f71dee43e715379e1da5d3bc9dbeb96b71a7&url=https://telegram.dog/newxxxiobot?start%3Dverify_Wt9l6CSwIq&alias=&format=json
[06-Sep-25 10:50:49 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 10:50:49 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 10:50:49 - INFO] - aiohttp.access - 172.31.97.194 [06/Sep/2025:10:50:49 +0000] "GET / HTTP/1.1" 200 178 "https://4a1152f9-f381-4535-9226-7b66706fd764-00-3hd4vkpolb01o.sisko.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Aree%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 10:59:32 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 10:59:32 - INFO] - bot - Bot stopped.
[06-Sep-25 10:59:37 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 10:59:37 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 10:59:38 - INFO] - aiohttp.access - 172.31.97.194 [06/Sep/2025:10:59:38 +0000] "GET / HTTP/1.1" 200 178 "https://4a1152f9-f381-4535-9226-7b66706fd764-00-3hd4vkpolb01o.sisko.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Arjs%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 11:03:17 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 11:03:28 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 11:03:28 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 11:03:29 - INFO] - aiohttp.access - 172.31.97.194 [06/Sep/2025:11:03:29 +0000] "GET / HTTP/1.1" 200 178 "https://4a1152f9-f381-4535-9226-7b66706fd764-00-3hd4vkpolb01o.sisko.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Arlt%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 11:08:36 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 11:08:37 - INFO] - bot - Bot stopped.
[06-Sep-25 11:08:45 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 11:08:45 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 11:08:45 - INFO] - aiohttp.access - 172.31.97.194 [06/Sep/2025:11:08:45 +0000] "GET / HTTP/1.1" 200 178 "https://4a1152f9-f381-4535-9226-7b66706fd764-00-3hd4vkpolb01o.sisko.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Arns%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 11:11:34 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 11:11:46 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 11:11:46 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 11:11:46 - INFO] - aiohttp.access - 172.31.97.194 [06/Sep/2025:11:11:46 +0000] "GET / HTTP/1.1" 200 178 "https://4a1152f9-f381-4535-9226-7b66706fd764-00-3hd4vkpolb01o.sisko.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Arpd%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[06-Sep-25 11:13:21 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[06-Sep-25 11:13:29 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[06-Sep-25 11:13:29 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[06-Sep-25 11:13:29 - INFO] - aiohttp.access - 172.31.97.194 [06/Sep/2025:11:13:29 +0000] "GET / HTTP/1.1" 200 178 "https://4a1152f9-f381-4535-9226-7b66706fd764-00-3hd4vkpolb01o.sisko.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Arrn%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[07-Sep-25 13:54:29 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[07-Sep-25 13:54:29 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[07-Sep-25 13:54:30 - INFO] - aiohttp.access - 172.31.118.2 [07/Sep/2025:13:54:30 +0000] "GET / HTTP/1.1" 200 178 "https://c5330233-5b07-4a3e-a8c6-039057820b1c-00-34rhmaqd1sz6o.sisko.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar1ig%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[07-Sep-25 13:54:58 - INFO] - aiohttp.access - 172.31.118.2 [07/Sep/2025:13:54:58 +0000] "GET / HTTP/1.1" 200 178 "https://c5330233-5b07-4a3e-a8c6-039057820b1c-00-34rhmaqd1sz6o.sisko.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar1r3%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[07-Sep-25 13:55:40 - INFO] - aiohttp.access - 172.31.118.2 [07/Sep/2025:13:55:40 +0000] "GET / HTTP/1.1" 200 178 "https://c5330233-5b07-4a3e-a8c6-039057820b1c-00-34rhmaqd1sz6o.sisko.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar2fb%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[07-Sep-25 14:01:59 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[07-Sep-25 14:02:13 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[07-Sep-25 14:02:13 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[07-Sep-25 14:02:15 - INFO] - aiohttp.access - 172.31.118.2 [07/Sep/2025:14:02:15 +0000] "GET / HTTP/1.1" 200 178 "https://c5330233-5b07-4a3e-a8c6-039057820b1c-00-34rhmaqd1sz6o.sisko.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar2mc%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
[07-Sep-25 14:03:42 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[07-Sep-25 14:03:51 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ultroid_official
[07-Sep-25 14:03:51 - INFO] - bot -  

       
(っ◔◡◔)っ ♥ ULTROIDOFFICIAL ♥
░╚════╝░░╚════╝░╚═════╝░╚══════╝
                                          
[07-Sep-25 14:03:51 - INFO] - aiohttp.access - 172.31.118.2 [07/Sep/2025:14:03:51 +0000] "GET / HTTP/1.1" 200 178 "https://c5330233-5b07-4a3e-a8c6-039057820b1c-00-34rhmaqd1sz6o.sisko.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=%3Ar2oc%3A" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
